title: Unbanked | Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://status.unbanked.com.br'
params:
  disableDarkMode: false
  shortDateFormat: '15:04 â€” Jan 2'
  down: '#e60000'
  systems:
    - name: Gateway
      category: North Coast
    - name: Backup Gateway
      category: East Coast
    - name: API
      description: The guts of the application.
      category: Uncategorized
    - name: Media Proxy
      description: >-
        This is the service responsible for serving images, audio, and video. It
        is reliant on our CDN.
      category: Uncategorized
  dateFormat: 'January 2, 2006 at 3:04 PM'
  brand: '#222222'
  headerTextColor: white
  logo: /img/logo-white.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: '#cc4400'
  notice: '#24478f'
  incidentHistoryFormat: yearly
  ok: '#008000'
  categories:
    - name: North Coast
      description: The main servers are located here.
      closed: true
    - name: East Coast
    - name: Uncategorized
      untitled: true
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
