title: Unbanked | Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://status.unbanked.com.br'
params:
  disableDarkMode: false
  shortDateFormat: '15:04 â€” Jan 2'
  down: '#e60000'
  systems:
    - name: API
      description: The core of our application.
      category: Uncategorized
    - name: Website
      category: Uncategorized
      description: Our frontend.
  dateFormat: 'January 2, 2006 at 3:04 PM'
  brand: '#222222'
  headerTextColor: white
  logo: /img/logo-white.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - link: 'https://uptime.unbanked.com.br'
      name: Uptime Monitor
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: '#cc4400'
  notice: '#24478f'
  incidentHistoryFormat: monthly
  ok: '#008000'
  categories:
    - name: Uncategorized
      untitled: true
      closed: false
    - name: Frontend
    - name: Backend
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
