title: Unbanked | Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://status.unbanked.com.br'
params:
  disableDarkMode: false
  shortDateFormat: '15:04 â€” Jan 2'
  down: '#e60000'
  systems:
    - name: API
      description: The core of our application.
      category: Uncategorized
    - name: Website
      category: Uncategorized
      description: Our frontend.
    - name: Google Pub/Sub
      category: Google Cloud Platform
    - name: Google Stackdriver
      category: Google Cloud Platform
    - name: Google Cloud Tasks
      category: Google Cloud Platform
    - category: Google Cloud Platform
      name: Google Compute Engine
    - category: Google Cloud Platform
      name: Google BigQuery
    - category: Google Cloud Platform
      name: Google Cloud Scheduler
    - category: Google Cloud Platform
      name: Google Container Registry
    - category: Google Cloud Platform
      name: Google Cloud Build
    - category: Google Cloud Platform
      name: Google Cloud Endpoints
    - category: Google Cloud Platform
      name: Google Cloud Run
    - name: Cloud Firestore
      category: Firebase
    - category: Firebase
      name: Cloud Functions
    - category: Firebase
      name: Authentication
    - category: Firebase
      name: Hosting
    - category: Firebase
      name: Cloud Storage
    - category: Firebase
      name: Google Analytics
    - category: Firebase
      name: Dynamic Links
    - category: Firebase
      name: Crashlytics
    - category: Firebase
      name: Performance Monitoring
    - category: Firebase
      name: Cloud Messaging
    - category: Firebase
      name: Predictions
    - category: Firebase
      name: ML Kit
  dateFormat: 'January 2, 2006 at 3:04 PM'
  brand: '#222222'
  headerTextColor: white
  logo: /img/logo-white.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - link: 'https://uptime.unbanked.com.br'
      name: Uptime Monitor
    - name: Google Cloud Status
      link: 'https://status.cloud.google.com'
    - name: Firebase Status
      link: 'https://status.firebase.google.com'
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: '#cc4400'
  notice: '#24478f'
  incidentHistoryFormat: monthly
  ok: '#008000'
  categories:
    - name: Uncategorized
      untitled: true
      closed: false
    - name: Comercial Environment
      description: Our production environment for the B2C segment.
    - name: Corporate Environment
      description: Our production environment for the B2B and B2B2C segments.
    - name: Google Cloud Platform
      description: Cloud provider for our services.
      closed: true
    - name: Firebase
      closed: true
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  useLargeHeaderDesign: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
